### ISSUE TITLE
Incorrect autofixing behaviour

### ISSUE THREAD

**Issue by kibertoad** [satazor/eslint-plugin-import-esm#3]
Thank you for implementing this awesome library!

It produces incorrect result in this case, however:

Original value:
```ts
export { something } from './src/client'
```

After autofixing:
```ts
export { something } from './src\client.js'
```

Slash shouldn't be changed when adding extension.

Note: I'm using Windows, but I'm not sure if this is affecting this behaviour

**Comment by kibertoad** [comment]
@satazor ping?

**Comment by satazor** [comment]
Thanks for the ping. I missed it. The issue lies in using path.sep, which on windows is \

Maybe switching from `path` to `path.posix` for all path methods solves the issue. Can you make a PR?

**Comment by kibertoad** [comment]
Sure, I can give it a shot
